spring:
    profiles:
        active: qa
    datasource:
        url: jdbc:postgresql://<qa-db-host>:5432/dbname
        username: qa_user
        password: qa_password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

jwt:
    secret: qa-secret-key-placeholder
    expiration: 3600000

app:
    regex:
        password: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$"
        message: La contraseña debe tener al menos 8 caracteres, incluyendo una mayúscula, una minúscula y un número.

logging:
    level:
        root: INFO
        org.hibernate.SQL: WARN
        org.springframework.web: INFO
        org.springframework.boot.autoconfigure: WARN
    file:
        name: logs/qa-app.log
