spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

app:
    regex:
        password: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$"
        message: La contraseña debe tener al menos 8 caracteres, incluyendo una mayúscula, una minúscula y un número.

logging:
    level:
        root: WARN
        org.springframework.web: ERROR
        org.hibernate: ERROR
        org.springdoc: ERROR
        org.springframework.boot.autoconfigure: ERROR
