server:
    port: 9191

spring:
    application:
        name: ms-challenge-app
    config:
        import: optional:file:D:/_PROGRAMAS/jboss-eap-7.3/standalone/configuration/ms-challenge-app.properties

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: always

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
