spring:
    datasource:
        url: jdbc:mysql://localhost:3306/DB_CHALLENGE
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

jwt:
    secret: nLkG3q9tv6qX5Yt1z0MjKfRMp7YkVpJ2X9LqOEj3W5k=
    expiration: 3600000

app:
    regex:
        password: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
        message: La contraseña debe tener al menos 8 caracteres, incluyendo una mayúscula, una minúscula, un número y un carácter especial.

logging:
    level:
        root: INFO
        org.springdoc: DEBUG
        org.hibernate.SQL: ERROR
        org.hibernate.type.descriptor.sql: TRACE
        org.springframework.boot.autoconfigure: INFO
        org.springframework.web: DEBUG
        org.springframework.web.servlet.DispatcherServlet: DEBUG
        org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: INFO
    file:
        name: logs/qa-app.log
